[package]
name = "world"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]

# uncomment these if compiling outside of 'pgrx'
# [profile.dev]
# panic = "unwind"

# lto = "fat"
# codegen-units = 1